name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10.14
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.14

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        source venv/bin/activate
        python manage.py migrate
        sleep 5

    - name: Collect static files
      run: |
        source venv/bin/activate
        python manage.py collectstatic --noinput

    - name: Download wait-for-it script
      run: |
        curl -sSL https://github.com/vishnubob/wait-for-it/raw/master/wait-for-it.sh -o wait-for-it.sh
        chmod +x wait-for-it.sh

    - name: Start Django server
      run: |
        source venv/bin/activate
        python manage.py runserver &
        ./wait-for-it.sh 127.0.0.1:8000 --timeout=30 -- echo "Django server is up"

    - name: Run tests
      run: |
        source venv/bin/activate
        python manage.py test

    - name: Register user
      run: |
        source venv/bin/activate
        curl -X POST http://127.0.0.1:8000/api/register/ \
          -H "Content-Type: application/json" \
          -d '{"username": "GitUser", "password": "password123"}'

    - name: Get token
      id: get_token
      run: |
        source venv/bin/activate
        response=$(curl -s -X POST http://127.0.0.1:8000/api/token/ -d "username=GitUser&password=password123")
        echo "token=$(echo $response | jq -r '.access')" >> $GITHUB_ENV

    - name: Process image
      run: |
        source venv/bin/activate
        curl -X POST http://127.0.0.1:8000/api/process-image/ \
          -H "Authorization: Bearer ${{ env.token }}" \
          -F "image=@input/1_Color.png"
